// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HRSystem.BaseLibrary.Models;

public  class RefreshToken
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(500)]
    public string Token { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Expires { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Created { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Revoked { get; set; }

    public int UserId { get; set; }

    [ForeignKey("UserId")]
    public virtual TPLUser User { get; set; }
}