// <auto-generated />
using System;
using HRSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRSystem.Infrastructure.Migrations
{
    [DbContext(typeof(HRSystemContext))]
    [Migration("20251029134915_AddRefreshTokens")]
    partial class AddRefreshTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.LKPLeaveType", b =>
                {
                    b.Property<int>("LeaveTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeductFromBalance")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int>("MaxDaysPerYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("RequiresMedicalNote")
                        .HasColumnType("bit");

                    b.HasKey("LeaveTypeId")
                        .HasName("PK_LeaveTypes");

                    b.ToTable("LKPLeaveTypes");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.LKPPermissionType", b =>
                {
                    b.Property<int>("permission_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("permission_type_id"));

                    b.Property<bool>("is_deductible")
                        .HasColumnType("bit");

                    b.Property<int>("monthly_limit_in_hours")
                        .HasColumnType("int");

                    b.Property<string>("permission_type_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("permission_type_id");

                    b.ToTable("LKPPermissionTypes");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.LKPSalary", b =>
                {
                    b.Property<int>("SalaryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalaryID"));

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Deductions")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly>("PayDate")
                        .HasColumnType("date");

                    b.HasKey("SalaryID")
                        .HasName("PK__LKPSalar__4BE204B719479BCC");

                    b.HasIndex("EmployeeID");

                    b.ToTable("LKPSalary");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.LkpBenefitType", b =>
                {
                    b.Property<int>("BenefitTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BenefitTypeID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("BenefitTypeID");

                    b.ToTable("LkpBenefitTypes");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.LkpGeneralDataBranch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_LkpBranches_IsDeleted");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("BranchId");

                    b.HasIndex("CompanyId");

                    b.ToTable("LkpGeneralDataBranches");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.LkpGeneralDataCompanyProfile", b =>
                {
                    b.Property<int>("CompanyProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyProfileId"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("CompanyCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FaxNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageURL")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("InsuranceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_LkpGeneralDataCompanyProfiles_IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("WebSite")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CompanyProfileId");

                    b.ToTable("LkpGeneralDataCompanyProfiles");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.LkpHRDepartment", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_LkpDepartments_IsDeleted");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("NameAr")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("DepartmentId")
                        .HasName("PK_LkpDepartments");

                    b.HasIndex("BranchId");

                    b.ToTable("LkpHRDepartments");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.LkpJobApplication", b =>
                {
                    b.Property<int>("JobApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobApplicationId"));

                    b.Property<DateTime>("ApplyDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CVFile")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CV_ID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .IsFixedLength();

                    b.Property<int>("JobID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("JobApplicationId");

                    b.HasIndex("CV_ID");

                    b.ToTable("LkpJobApplication");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__RefreshT__3214EC07E7828848");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLAssetManagement", b =>
                {
                    b.Property<int>("AssetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetID"));

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("AssignedDate")
                        .HasColumnType("date");

                    b.Property<int>("AssignedTo")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ReturnDate")
                        .HasColumnType("date");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AssetID")
                        .HasName("PK__TPLAsset__434923721A60BBB8");

                    b.HasIndex("AssignedTo");

                    b.ToTable("TPLAssetManagement");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLAttendance", b =>
                {
                    b.Property<int>("AttendanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceID"));

                    b.Property<TimeOnly?>("CheckIn")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("CheckOut")
                        .HasColumnType("time");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AttendanceID")
                        .HasName("PK__TPLAtten__8B69263C191476DC");

                    b.HasIndex("EmployeeID");

                    b.ToTable("TPLAttendance");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLBenefitsCompensation", b =>
                {
                    b.Property<int>("BenefitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BenefitID"));

                    b.Property<int>("BenefitTypeID")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("BenefitID")
                        .HasName("PK__Benefits__5754C53AEB6B105B");

                    b.HasIndex("BenefitTypeID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("TPLBenefitsCompensation");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLCVBank", b =>
                {
                    b.Property<int>("CV_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CV_ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CV_File")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CV_ID");

                    b.ToTable("TPLCVBank");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLCandidate", b =>
                {
                    b.Property<int>("CandidateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CandidateID"));

                    b.Property<int>("JobApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CandidateID")
                        .HasName("PK__TPLCandi__DF539BFC3A8F1883");

                    b.HasIndex("JobApplicationId");

                    b.ToTable("TPLCandidate");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLDisciplinaryAction", b =>
                {
                    b.Property<int>("ActionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActionID"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TakenBy")
                        .HasColumnType("int");

                    b.HasKey("ActionID")
                        .HasName("PK__TPLDisci__FFE3F4B90953BFED");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("TakenBy");

                    b.ToTable("TPLDisciplinaryActions");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLDocumentManagement", b =>
                {
                    b.Property<int>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentID"));

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("UploadDate")
                        .HasColumnType("date");

                    b.HasKey("DocumentID")
                        .HasName("PK__TPLDocum__1ABEEF6F44C1B7DC");

                    b.HasIndex("EmployeeID");

                    b.ToTable("TPLDocumentManagement");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLEmployee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<int>("JobID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EmployeeID")
                        .HasName("PK__Employee__7AD04FF148254588");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("JobID");

                    b.HasIndex(new[] { "Email" }, "UQ__Employee__A9D1053436BBDCA7")
                        .IsUnique();

                    b.ToTable("TPLEmployee");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLEmployee_Training", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("TrainingID")
                        .HasColumnType("int");

                    b.Property<string>("CompletionStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("EmployeeID", "TrainingID")
                        .HasName("PK__TPLEmplo__445D3E2F19C3B2EB");

                    b.HasIndex("TrainingID");

                    b.ToTable("TPLEmployee_Training");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLEvaluationCriterion", b =>
                {
                    b.Property<int>("CriteriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CriteriaID"));

                    b.Property<string>("CriteriaName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("CriteriaID");

                    b.ToTable("TPLEvaluationCriteria");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLHRNeedRequest", b =>
                {
                    b.Property<int>("HRNeedID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HRNeedID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("HRNeedID")
                        .HasName("PK_HRNeedRequests");

                    b.HasIndex("DepartmentId");

                    b.ToTable("TPLHRNeedRequests");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLInterview", b =>
                {
                    b.Property<int>("InterviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterviewID"));

                    b.Property<int>("CandidateID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InterviewerID")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("InterviewID")
                        .HasName("PK__Intervie__C97C5832B0092694");

                    b.HasIndex("CandidateID");

                    b.HasIndex("InterviewerID");

                    b.ToTable("TPLInterview");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLJob", b =>
                {
                    b.Property<int>("JobID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobID"));

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("PostedDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("JobID")
                        .HasName("PK__TPLJob__056690E20F0CC5B9");

                    b.ToTable("TPLJob");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLLeave", b =>
                {
                    b.Property<int>("LeaveID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveID"));

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("request_id")
                        .HasColumnType("int");

                    b.HasKey("LeaveID")
                        .HasName("PK__Leave__796DB97974021ABD");

                    b.HasIndex(new[] { "request_id" }, "IX_Leave")
                        .IsUnique();

                    b.ToTable("TPLLeave");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLLeaveBalance", b =>
                {
                    b.Property<int>("BalanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BalanceId"));

                    b.Property<int>("AllocatedDays")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<int>("UsedDays")
                        .HasColumnType("int");

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("BalanceId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("TPLLeaveBalance");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLOffboarding", b =>
                {
                    b.Property<int>("ExitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExitID"));

                    b.Property<string>("ClearanceStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("ExitInterviewNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExitReason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("ResignationDate")
                        .HasColumnType("date");

                    b.HasKey("ExitID")
                        .HasName("PK__TPLOffbo__26D64E9808277847");

                    b.HasIndex("EmployeeID");

                    b.ToTable("TPLOffboarding");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLOnboarding", b =>
                {
                    b.Property<int>("OnboardingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OnboardingID"));

                    b.Property<string>("AssignedMentor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChecklistStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("OnboardingID")
                        .HasName("PK__Onboardi__43F2371E2B631C75");

                    b.HasIndex("EmployeeID");

                    b.ToTable("TPLOnboarding");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLPerformanceEvaluation", b =>
                {
                    b.Property<int>("EvaluationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvaluationID"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CriteriaID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("EvaluationID")
                        .HasName("PK__TPLPerfo__36AE68D36D7296F8");

                    b.HasIndex("CriteriaID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("TPLPerformanceEvaluation");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLPermission", b =>
                {
                    b.Property<int>("permission_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("permission_id"));

                    b.Property<int>("employee_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("end_time")
                        .HasColumnType("datetime");

                    b.Property<int>("permission_type_id")
                        .HasColumnType("int");

                    b.Property<string>("reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("request_date")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("start_time")
                        .HasColumnType("datetime");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("total_hours")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("permission_id");

                    b.HasIndex("employee_id");

                    b.HasIndex("permission_type_id");

                    b.ToTable("TPLPermissions");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLProject", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectID"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int?>("ManagerID")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("ProjectID")
                        .HasName("PK__TPLProje__761ABED0A98D3175");

                    b.HasIndex("ManagerID");

                    b.ToTable("TPLProject");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLProject_Assignment", b =>
                {
                    b.Property<int>("assignment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("assignment_id"));

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<int>("HoursWorked")
                        .HasColumnType("int");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<string>("RoleInProject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("assignment_id");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("ProjectID");

                    b.ToTable("TPLProject_Assignment");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLRecruitmentPortal", b =>
                {
                    b.Property<int>("PortalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PortalID"));

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<int>("HRNeedID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("PublishDate")
                        .HasColumnType("date");

                    b.HasKey("PortalID")
                        .HasName("PK__TPLRecru__B87D58338DAADC9C");

                    b.HasIndex("HRNeedID");

                    b.ToTable("TPLRecruitmentPortal");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLRequest", b =>
                {
                    b.Property<int>("request_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("request_id"));

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<int>("employee_id")
                        .HasColumnType("int");

                    b.Property<DateOnly>("end_date")
                        .HasColumnType("date");

                    b.Property<int>("leave_type_id")
                        .HasColumnType("int");

                    b.Property<int>("number_of_days")
                        .HasColumnType("int");

                    b.Property<DateOnly>("start_date")
                        .HasColumnType("date");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<DateTime>("submission_date")
                        .HasColumnType("datetime");

                    b.HasKey("request_id");

                    b.HasIndex("employee_id");

                    b.HasIndex("leave_type_id");

                    b.ToTable("TPLRequests");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLSelfServiceRequest", b =>
                {
                    b.Property<int>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestID"));

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("RequestDate")
                        .HasColumnType("date");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RequestID")
                        .HasName("PK__TPLSelfS__33A8519A2AA9D005");

                    b.HasIndex("EmployeeID");

                    b.ToTable("TPLSelfServiceRequests");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLSurvey", b =>
                {
                    b.Property<int>("SurveyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SurveyID"));

                    b.Property<DateOnly>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SurveyID")
                        .HasName("PK__TPLSurve__A5481F9D7B7BA7D2");

                    b.ToTable("TPLSurvey");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLSurvey_Response", b =>
                {
                    b.Property<int>("ResponseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResponseID"));

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ResponseText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SurveyID")
                        .HasColumnType("int");

                    b.HasKey("ResponseID")
                        .HasName("PK__TPLSurve__1AAA640CF9F8B7BF");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("SurveyID");

                    b.ToTable("TPLSurvey_Response");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLTraining", b =>
                {
                    b.Property<int>("TrainingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainingID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TrainingID")
                        .HasName("PK__TPLTrain__E8D71DE221E8C971");

                    b.ToTable("TPLTraining");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLUser", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserID")
                        .HasName("PK__User__1788CCAC2EB55247");

                    b.HasIndex(new[] { "EmployeeID" }, "IX_User")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "UQ__User__536C85E4A1E9872A")
                        .IsUnique();

                    b.ToTable("TPLUser");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.LKPSalary", b =>
                {
                    b.HasOne("HRSystem.BaseLibrary.Models.TPLEmployee", "Employee")
                        .WithMany("LKPSalaries")
                        .HasForeignKey("EmployeeID")
                        .IsRequired()
                        .HasConstraintName("FK_LKPSalary_TPLEmployee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.LkpGeneralDataBranch", b =>
                {
                    b.HasOne("HRSystem.BaseLibrary.Models.LkpGeneralDataCompanyProfile", "Company")
                        .WithMany("LkpGeneralDataBranches")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK_LkpGeneralDataBranches_LkpGeneralDataCompanyProfiles");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.LkpHRDepartment", b =>
                {
                    b.HasOne("HRSystem.BaseLibrary.Models.LkpGeneralDataBranch", "Branch")
                        .WithMany("LkpHRDepartments")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK_LkpHRDepartments_LkpGeneralDataBranches");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.LkpJobApplication", b =>
                {
                    b.HasOne("HRSystem.BaseLibrary.Models.TPLCVBank", "CV")
                        .WithMany("LkpJobApplications")
                        .HasForeignKey("CV_ID")
                        .HasConstraintName("FK_LkpJobApplication_TPLCVBank");

                    b.Navigation("CV");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.RefreshToken", b =>
                {
                    b.HasOne("HRSystem.BaseLibrary.Models.TPLUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLAssetManagement", b =>
                {
                    b.HasOne("HRSystem.BaseLibrary.Models.TPLEmployee", "AssignedToNavigation")
                        .WithMany("TPLAssetManagements")
                        .HasForeignKey("AssignedTo")
                        .IsRequired()
                        .HasConstraintName("FK_TPLAssetManagement_TPLEmployee");

                    b.Navigation("AssignedToNavigation");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLAttendance", b =>
                {
                    b.HasOne("HRSystem.BaseLibrary.Models.TPLEmployee", "Employee")
                        .WithMany("TPLAttendances")
                        .HasForeignKey("EmployeeID")
                        .IsRequired()
                        .HasConstraintName("FK_TPLAttendance_TPLEmployee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLBenefitsCompensation", b =>
                {
                    b.HasOne("HRSystem.BaseLibrary.Models.LkpBenefitType", "BenefitType")
                        .WithMany("TPLBenefitsCompensations")
                        .HasForeignKey("BenefitTypeID")
                        .IsRequired()
                        .HasConstraintName("FK_TPLBenefitsCompensation_LkpBenefitTypes");

                    b.HasOne("HRSystem.BaseLibrary.Models.TPLEmployee", "Employee")
                        .WithMany("TPLBenefitsCompensations")
                        .HasForeignKey("EmployeeID")
                        .IsRequired()
                        .HasConstraintName("FK_TPLBenefitsCompensation_TPLEmployee");

                    b.Navigation("BenefitType");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLCandidate", b =>
                {
                    b.HasOne("HRSystem.BaseLibrary.Models.LkpJobApplication", "JobApplication")
                        .WithMany("TPLCandidates")
                        .HasForeignKey("JobApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK_TPLCandidate_LkpJobApplication");

                    b.Navigation("JobApplication");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLDisciplinaryAction", b =>
                {
                    b.HasOne("HRSystem.BaseLibrary.Models.TPLEmployee", "Employee")
                        .WithMany("TPLDisciplinaryActionEmployees")
                        .HasForeignKey("EmployeeID")
                        .IsRequired()
                        .HasConstraintName("FK_TPLDisciplinaryActions_Employee1");

                    b.HasOne("HRSystem.BaseLibrary.Models.TPLEmployee", "TakenByNavigation")
                        .WithMany("TPLDisciplinaryActionTakenByNavigations")
                        .HasForeignKey("TakenBy")
                        .IsRequired()
                        .HasConstraintName("FK_TPLDisciplinaryActions_Employee");

                    b.Navigation("Employee");

                    b.Navigation("TakenByNavigation");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLDocumentManagement", b =>
                {
                    b.HasOne("HRSystem.BaseLibrary.Models.TPLEmployee", "Employee")
                        .WithMany("TPLDocumentManagements")
                        .HasForeignKey("EmployeeID")
                        .IsRequired()
                        .HasConstraintName("FK_TPLDocumentManagement_Employee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLEmployee", b =>
                {
                    b.HasOne("HRSystem.BaseLibrary.Models.LkpHRDepartment", "Department")
                        .WithMany("TPLEmployees")
                        .HasForeignKey("DepartmentID")
                        .IsRequired()
                        .HasConstraintName("FK_TPLEmployee_LkpHRDepartments");

                    b.HasOne("HRSystem.BaseLibrary.Models.TPLJob", "Job")
                        .WithMany("TPLEmployees")
                        .HasForeignKey("JobID")
                        .IsRequired()
                        .HasConstraintName("FK_TPLEmployee_Job");

                    b.Navigation("Department");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLEmployee_Training", b =>
                {
                    b.HasOne("HRSystem.BaseLibrary.Models.TPLEmployee", "Employee")
                        .WithMany("TPLEmployee_Trainings")
                        .HasForeignKey("EmployeeID")
                        .IsRequired()
                        .HasConstraintName("FK_TPLEmployee_Training_TPLEmployee");

                    b.HasOne("HRSystem.BaseLibrary.Models.TPLTraining", "Training")
                        .WithMany("TPLEmployee_Trainings")
                        .HasForeignKey("TrainingID")
                        .IsRequired()
                        .HasConstraintName("FK__TPLEmploy__Train__2180FB33");

                    b.Navigation("Employee");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLHRNeedRequest", b =>
                {
                    b.HasOne("HRSystem.BaseLibrary.Models.LkpHRDepartment", "Department")
                        .WithMany("TPLHRNeedRequests")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK_TPLHRNeedRequests_LkpHRDepartments");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLInterview", b =>
                {
                    b.HasOne("HRSystem.BaseLibrary.Models.TPLCandidate", "Candidate")
                        .WithMany("TPLInterviews")
                        .HasForeignKey("CandidateID")
                        .IsRequired()
                        .HasConstraintName("FK_TPLInterview_TPLCandidate");

                    b.HasOne("HRSystem.BaseLibrary.Models.TPLEmployee", "Interviewer")
                        .WithMany("TPLInterviews")
                        .HasForeignKey("InterviewerID")
                        .IsRequired()
                        .HasConstraintName("FK_TPLInterview_TPLEmployee1");

                    b.Navigation("Candidate");

                    b.Navigation("Interviewer");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLLeave", b =>
                {
                    b.HasOne("HRSystem.BaseLibrary.Models.TPLRequest", "request")
                        .WithOne("TPLLeave")
                        .HasForeignKey("HRSystem.BaseLibrary.Models.TPLLeave", "request_id")
                        .IsRequired()
                        .HasConstraintName("FK_TPLLeave_TPLRequests");

                    b.Navigation("request");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLLeaveBalance", b =>
                {
                    b.HasOne("HRSystem.BaseLibrary.Models.TPLEmployee", "Employee")
                        .WithMany("TPLLeaveBalances")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_TPLLeaveBalance_TPLEmployee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLOffboarding", b =>
                {
                    b.HasOne("HRSystem.BaseLibrary.Models.TPLEmployee", "Employee")
                        .WithMany("TPLOffboardings")
                        .HasForeignKey("EmployeeID")
                        .IsRequired()
                        .HasConstraintName("FK_TPLOffboarding_TPLEmployee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLOnboarding", b =>
                {
                    b.HasOne("HRSystem.BaseLibrary.Models.TPLEmployee", "Employee")
                        .WithMany("TPLOnboardings")
                        .HasForeignKey("EmployeeID")
                        .IsRequired()
                        .HasConstraintName("FK_TPLOnboarding_TPLEmployee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLPerformanceEvaluation", b =>
                {
                    b.HasOne("HRSystem.BaseLibrary.Models.TPLEvaluationCriterion", "Criteria")
                        .WithMany("TPLPerformanceEvaluations")
                        .HasForeignKey("CriteriaID")
                        .IsRequired()
                        .HasConstraintName("FK_TPLPerformanceEvaluation_TPLEvaluationCriteria");

                    b.HasOne("HRSystem.BaseLibrary.Models.TPLEmployee", "Employee")
                        .WithMany("TPLPerformanceEvaluations")
                        .HasForeignKey("EmployeeID")
                        .IsRequired()
                        .HasConstraintName("FK_TPLPerformanceEvaluation_TPLEmployee2");

                    b.Navigation("Criteria");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLPermission", b =>
                {
                    b.HasOne("HRSystem.BaseLibrary.Models.TPLEmployee", "employee")
                        .WithMany("TPLPermissions")
                        .HasForeignKey("employee_id")
                        .IsRequired()
                        .HasConstraintName("FK_TPLPermissions_TPLEmployee");

                    b.HasOne("HRSystem.BaseLibrary.Models.LKPPermissionType", "permission_type")
                        .WithMany("TPLPermissions")
                        .HasForeignKey("permission_type_id")
                        .IsRequired()
                        .HasConstraintName("FK_TPLPermissions_LKPPermissionTypes");

                    b.Navigation("employee");

                    b.Navigation("permission_type");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLProject", b =>
                {
                    b.HasOne("HRSystem.BaseLibrary.Models.TPLEmployee", "Manager")
                        .WithMany("TPLProjects")
                        .HasForeignKey("ManagerID")
                        .HasConstraintName("FK_TPLProject_Manager");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLProject_Assignment", b =>
                {
                    b.HasOne("HRSystem.BaseLibrary.Models.TPLEmployee", "Employee")
                        .WithMany("TPLProject_Assignments")
                        .HasForeignKey("EmployeeID")
                        .IsRequired()
                        .HasConstraintName("FK_TPLProject_Assignment_TPLEmployee");

                    b.HasOne("HRSystem.BaseLibrary.Models.TPLProject", "Project")
                        .WithMany("TPLProject_Assignments")
                        .HasForeignKey("ProjectID")
                        .IsRequired()
                        .HasConstraintName("FK_TPLProject_Assignment_TPLProject");

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLRecruitmentPortal", b =>
                {
                    b.HasOne("HRSystem.BaseLibrary.Models.TPLHRNeedRequest", "HRNeed")
                        .WithMany("TPLRecruitmentPortals")
                        .HasForeignKey("HRNeedID")
                        .IsRequired()
                        .HasConstraintName("FK_TPLRecruitmentPortal_TPLHRNeedRequests");

                    b.Navigation("HRNeed");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLRequest", b =>
                {
                    b.HasOne("HRSystem.BaseLibrary.Models.TPLEmployee", "employee")
                        .WithMany("TPLRequests")
                        .HasForeignKey("employee_id")
                        .IsRequired()
                        .HasConstraintName("FK_TPLRequests_TPLEmployee");

                    b.HasOne("HRSystem.BaseLibrary.Models.LKPLeaveType", "leave_type")
                        .WithMany("TPLRequests")
                        .HasForeignKey("leave_type_id")
                        .IsRequired()
                        .HasConstraintName("FK_TPLRequests_LKPLeaveTypes");

                    b.Navigation("employee");

                    b.Navigation("leave_type");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLSelfServiceRequest", b =>
                {
                    b.HasOne("HRSystem.BaseLibrary.Models.TPLEmployee", "Employee")
                        .WithMany("TPLSelfServiceRequests")
                        .HasForeignKey("EmployeeID")
                        .IsRequired()
                        .HasConstraintName("FK_TPLSelfServiceRequests_TPLEmployee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLSurvey_Response", b =>
                {
                    b.HasOne("HRSystem.BaseLibrary.Models.TPLEmployee", "Employee")
                        .WithMany("TPLSurvey_Responses")
                        .HasForeignKey("EmployeeID")
                        .IsRequired()
                        .HasConstraintName("FK_TPLSurvey_Response_TPLEmployee");

                    b.HasOne("HRSystem.BaseLibrary.Models.TPLSurvey", "Survey")
                        .WithMany("TPLSurvey_Responses")
                        .HasForeignKey("SurveyID")
                        .IsRequired()
                        .HasConstraintName("FK__TPLSurvey__Surve__31B762FC");

                    b.Navigation("Employee");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLUser", b =>
                {
                    b.HasOne("HRSystem.BaseLibrary.Models.TPLEmployee", "Employee")
                        .WithOne("TPLUser")
                        .HasForeignKey("HRSystem.BaseLibrary.Models.TPLUser", "EmployeeID")
                        .IsRequired()
                        .HasConstraintName("FK_TPLUser_TPLEmployee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.LKPLeaveType", b =>
                {
                    b.Navigation("TPLRequests");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.LKPPermissionType", b =>
                {
                    b.Navigation("TPLPermissions");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.LkpBenefitType", b =>
                {
                    b.Navigation("TPLBenefitsCompensations");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.LkpGeneralDataBranch", b =>
                {
                    b.Navigation("LkpHRDepartments");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.LkpGeneralDataCompanyProfile", b =>
                {
                    b.Navigation("LkpGeneralDataBranches");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.LkpHRDepartment", b =>
                {
                    b.Navigation("TPLEmployees");

                    b.Navigation("TPLHRNeedRequests");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.LkpJobApplication", b =>
                {
                    b.Navigation("TPLCandidates");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLCVBank", b =>
                {
                    b.Navigation("LkpJobApplications");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLCandidate", b =>
                {
                    b.Navigation("TPLInterviews");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLEmployee", b =>
                {
                    b.Navigation("LKPSalaries");

                    b.Navigation("TPLAssetManagements");

                    b.Navigation("TPLAttendances");

                    b.Navigation("TPLBenefitsCompensations");

                    b.Navigation("TPLDisciplinaryActionEmployees");

                    b.Navigation("TPLDisciplinaryActionTakenByNavigations");

                    b.Navigation("TPLDocumentManagements");

                    b.Navigation("TPLEmployee_Trainings");

                    b.Navigation("TPLInterviews");

                    b.Navigation("TPLLeaveBalances");

                    b.Navigation("TPLOffboardings");

                    b.Navigation("TPLOnboardings");

                    b.Navigation("TPLPerformanceEvaluations");

                    b.Navigation("TPLPermissions");

                    b.Navigation("TPLProject_Assignments");

                    b.Navigation("TPLProjects");

                    b.Navigation("TPLRequests");

                    b.Navigation("TPLSelfServiceRequests");

                    b.Navigation("TPLSurvey_Responses");

                    b.Navigation("TPLUser");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLEvaluationCriterion", b =>
                {
                    b.Navigation("TPLPerformanceEvaluations");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLHRNeedRequest", b =>
                {
                    b.Navigation("TPLRecruitmentPortals");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLJob", b =>
                {
                    b.Navigation("TPLEmployees");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLProject", b =>
                {
                    b.Navigation("TPLProject_Assignments");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLRequest", b =>
                {
                    b.Navigation("TPLLeave");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLSurvey", b =>
                {
                    b.Navigation("TPLSurvey_Responses");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLTraining", b =>
                {
                    b.Navigation("TPLEmployee_Trainings");
                });

            modelBuilder.Entity("HRSystem.BaseLibrary.Models.TPLUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
