using System;
using System.ComponentModel.DataAnnotations;
using System.Text.RegularExpressions;

namespace HRSystem.BaseLibrary.DTOs
{
    // =================================================================================
    // 1. READ DTO (OUTPUT): Data sent to the Frontend (GET Requests)
    // =================================================================================

    public class CompanyProfileReadDto
    {
        // Primary Key for identification
        public int CompanyProfileId { get; set; }

        // General Info
        public string NameEn { get; set; }
        public string InsuranceNumber { get; set; }
        public string TaxNumber { get; set; }

        // Contact Details
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public string Address { get; set; }
        public string ImageURL { get; set; }

        // Audit Field
        public int CreatedBy { get; set; }
    }

    // =================================================================================
    // 2. CREATE DTO (INPUT): Data received to create a new record (POST)
    // =================================================================================

    public class CompanyProfileCreateDto
    {
        // Name validation
        [Required(ErrorMessage = "Name is required.")]
        [StringLength(150, ErrorMessage = "Name cannot exceed 150 characters.")]
        public string NameEn { get; set; }

        // Insurance Number validation (Assuming 10 digits only)
        [Required(ErrorMessage = "Insurance Number is required.")]
        [RegularExpression(@"^\d{10}$", ErrorMessage = "Insurance Number must be 10 digits.")]
        public string InsuranceNumber { get; set; }

        // Tax Number validation
        [Required(ErrorMessage = "Tax Number is required.")]
        [StringLength(15, ErrorMessage = "Tax Number cannot exceed 15 characters.")]
        public string TaxNumber { get; set; }

        // Contact validation
        [Required(ErrorMessage = "Phone Number is required.")]
        [Phone(ErrorMessage = "Invalid phone number format.")]
        [StringLength(50)]
        public string PhoneNumber { get; set; }

        [StringLength(50)]
        public string FaxNumber { get; set; }

        [Required(ErrorMessage = "Email is required.")]
        [EmailAddress(ErrorMessage = "Invalid email address format.")]
        [StringLength(100)]
        public string Email { get; set; }

        // Website/Address
        [Url(ErrorMessage = "Invalid website URL format.")]
        [StringLength(200)]
        public string WebSite { get; set; }

        [StringLength(300)]
        public string Address { get; set; }

        // Optional Audit and Code fields (if not auto-generated by the backend)
        public Guid CompanyCode { get; set; }
    }

    // =================================================================================
    // 3. UPDATE DTO (INPUT): Data received to modify an existing record (PUT/PATCH)
    // =================================================================================

    public class CompanyProfileUpdateDto : CompanyProfileCreateDto
    {
        // The ID is required to identify the record being updated
        [Required(ErrorMessage = "CompanyProfileId is required for update.")]
        public int CompanyProfileId { get; set; }

        // We inherit all other properties (Name, Phone, Email, etc.) from CreateDto
    }
}
